name: MYTV

on:
  schedule:
    - cron: '0 5 * * *'  # 每天凌晨5点触发
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
      donotpublish:
        description: '构建后不提交发布新版'
        required: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for new commits
        id: check_commits
        run: |
          latest_commit=$(git log -1 --format='%H')
          echo "Latest commit: $latest_commit"
          
          # For manual triggers, we don't need to check for new commits
          if ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.rebuild != 'true' }}; then
            echo "Manual trigger without rebuild flag. Continuing build process."
          elif [ -z "${{ github.event.before }}" ]; then
            echo "This is the first run. Continuing build process."
          else
            previous_run_commit=${{ github.event.before }}
            echo "Previous run commit: $previous_run_commit"
            if [ "$latest_commit" = "$previous_run_commit" ]; then
              echo "No new commits since last run. Exiting."
              exit 1
            else
              echo "New commits detected. Continuing build process."
            fi
          fi

      - name: Set up JDK 21
        if: success()
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Get History
        if: success()
        run: |
          chmod +x history.sh
          output=$(./history.sh)
          echo "$output" > history.md

      - name: Create Release
        if: success() && github.event_name != 'workflow_dispatch' && github.ref != 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: history.md

      - name: Run build with Gradle wrapper
        if: success()
        run: |
          ./gradlew clean
          ./gradlew assembleRelease -Pnet=common

      - name: Sign app APK
        if: success()
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.ALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Release Asset
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.sign_app.outputs.signedReleaseFile }}
          asset_name: my-tv-0.main.apk
          asset_content_type: application/vnd.android.package-archive

      # Additional steps for mobile and ipv6 builds can be added here

      - name: Run build with Gradle wrapper mobile
        if: success()
        run: |
          ./gradlew clean
          ./gradlew assembleRelease -Pnet=mobile

      - name: Sign app APK mobile
        if: success()
        id: sign_app_mobile
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.ALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Release Asset mobile
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.sign_app_mobile.outputs.signedReleaseFile }}
          asset_name: my-tv-0.main.mobile.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Run build with Gradle wrapper ipv6
        if: success()
        run: |
          ./gradlew clean
          ./gradlew assembleRelease -Pnet=ipv6

      - name: Sign app APK ipv6
        if: success()
        id: sign_app_ipv6
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.ALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Release Asset ipv6
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.sign_app_ipv6.outputs.signedReleaseFile }}
          asset_name: my-tv-0.main.ipv6.apk
          asset_content_type: application/vnd.android.package-archive